In [1]:
import requests
import pandas as pd

# API base URL
API_BASE_URL = "https://bible.peplamb.com/api/parse"

# List of Farsi book names and their English counterparts from the PDF
farsi_books = [
    ("پيدايش", "Genesis"),
    ("سفر خروج", "Exodus"),
    ("لويان", "Leviticus"),
    ("اعداد", "Numbers"),
    ("تثنييه", "Deuteronomy"),
    ("يشوع", "Joshua"),
    ("داوران", "Judges"),
    ("روت", "Ruth"),
    ("اول سموئيل", "1 Samuel"),
    ("دوم سموئيل", "2 Samuel"),
    ("اول پادشاهان", "1 Kings"),
    ("دوم پادشاهان", "2 Kings"),
    ("اول تواريخ", "1 Chronicles"),
    ("دوم تواريخ", "2 Chronicles"),
    ("عزرا", "Ezra"),
    ("نحيميا", "Nehemiah"),
    ("استر", "Esther"),
    ("ايوب", "Job"),
    ("مزامير", "Psalms"),
    ("امثالا", "Proverbs"),
    ("جامعه", "Ecclesiastes"),
    ("غزلی از غزلها", "Song of Solomon"),
    ("اشعيا", "Isaiah"),
    ("ارمييا", "Jeremiah"),
    ("نوحه", "Lamentations"),
    ("حزقيال", "Ezekiel"),
    ("دانيال", "Daniel"),
    ("هوزيا", "Hosea"),
    ("يوئيل", "Joel"),
    ("عاموس", "Amos"),
    ("عوبيديا", "Obadiah"),
    ("يونس", "Jonah"),
    ("ميکاه", "Micah"),
    ("ناحوم", "Nahum"),
    ("حبقوق", "Habakkuk"),
    ("ضفينيا", "Zephaniah"),
    ("حجی", "Haggai"),
    ("زکريا", "Zechariah"),
    ("ملکی", "Malachi"),
    ("متی", "Matthew"),
    ("مرقس", "Mark"),
    ("لوقا", "Luke"),
    ("يوحنا", "John"),
    ("اعمال رسولن", "Acts"),
    ("روميان", "Romans"),
    ("اول قرنتيان", "1 Corinthians"),
    ("دوم قرنتيان", "2 Corinthians"),
    ("غلطيان", "Galatians"),
    ("افسسيان", "Ephesians"),
    ("فيليپيان", "Philippians"),
    ("کولوسيان", "Colossians"),
    ("اول تسالونيکيان", "1 Thessalonians"),
    ("دوم تسالونيکيان", "2 Thessalonians"),
    ("اول تيموتيوس", "1 Timothy"),
    ("دوم تيموتيوس", "2 Timothy"),
    ("تايتوس", "Titus"),
    ("فيلمان", "Philemon"),
    ("عبرانيان", "Hebrews"),
    ("يعقوب", "James"),
    ("اول پترس", "1 Peter"),
    ("دوم پترس", "2 Peter"),
    ("اول يوحنا", "1 John"),
    ("دوم يوحنا", "2 John"),
    ("سوم يوحنا", "3 John"),
    ("يهودا", "Jude"),
    ("مکاشفه", "Revelation"),
]

# Check each book using the API and collect results for books with length 0
books_with_bad_parse = []
books_with_good_parse = []
bad_count = 0

for farsi, english in farsi_books:
    #farsi = farsi_to_dari(farsi)
    params = {
        "references": farsi,
        "splitRange": "true",
    }
    try:
        response = requests.get(API_BASE_URL, params=params, timeout=10)
        if response.status_code == 200:
            data = response.json()
            if len(data) == 0:
                bad_count = bad_count + 1
                print(f"Book with no parsed references: {bad_count} - {farsi} ({english})")
                books_with_bad_parse.append((farsi, english))
            else:
                books_with_good_parse.append((farsi, english))
        else:
            print(f"Error {response.status_code} for {farsi} ({english}): {response.text}")
    except requests.exceptions.RequestException as e:
        print(f"Request failed for {farsi} ({english}): {e}")

# Output results as a table
#print("Books with no parse results:")
df_farsi_bad = pd.DataFrame(books_with_bad_parse, columns=["Farsi Name", "English Name"])
#print("Books with good parse results:")
df_farsi_good = pd.DataFrame(books_with_good_parse, columns=["Farsi Name", "English Name"])

Book with no parsed references: 1 - لويان (Leviticus)
Book with no parsed references: 2 - تثنييه (Deuteronomy)
Book with no parsed references: 3 - نحيميا (Nehemiah)
Book with no parsed references: 4 - ايوب (Job)
Book with no parsed references: 5 - مزامير (Psalms)
Book with no parsed references: 6 - امثالا (Proverbs)
Book with no parsed references: 7 - ارمييا (Jeremiah)
Book with no parsed references: 8 - نوحه (Lamentations)
Book with no parsed references: 9 - هوزيا (Hosea)
Book with no parsed references: 10 - عوبيديا (Obadiah)
Book with no parsed references: 11 - يونس (Jonah)
Book with no parsed references: 12 - ضفينيا (Zephaniah)
Book with no parsed references: 13 - زکريا (Zechariah)
Book with no parsed references: 14 - غلطيان (Galatians)
Book with no parsed references: 15 - افسسيان (Ephesians)
Book with no parsed references: 16 - فيليپيان (Philippians)
Book with no parsed references: 17 - کولوسيان (Colossians)
Book with no parsed references: 18 - اول تيموتيوس (1 Timothy)
Book with no parsed references: 19 - دوم تيموتيوس (2 Timothy)
Book with no parsed references: 20 - تايتوس (Titus)
Book with no parsed references: 21 - فيلمان (Philemon)
Book with no parsed references: 22 - اول پترس (1 Peter)
Book with no parsed references: 23 - دوم پترس (2 Peter)
Book with no parsed references: 24 - يهودا (Jude)

In [2]:
df_farsi_bad

      Farsi Name  English Name
0          لويان     Leviticus
1         تثنييه   Deuteronomy
2         نحيميا      Nehemiah
3           ايوب           Job
4         مزامير        Psalms
5         امثالا      Proverbs
6         ارمييا      Jeremiah
7           نوحه  Lamentations
8          هوزيا         Hosea
9        عوبيديا       Obadiah
10          يونس         Jonah
11        ضفينيا     Zephaniah
12         زکريا     Zechariah
13        غلطيان     Galatians
14       افسسيان     Ephesians
15      فيليپيان   Philippians
16      کولوسيان    Colossians
17  اول تيموتيوس     1 Timothy
18  دوم تيموتيوس     2 Timothy
19        تايتوس         Titus
20        فيلمان      Philemon
21      اول پترس       1 Peter
22      دوم پترس       2 Peter
23         يهودا          Jude

In [3]:
import requests
import pandas as pd

# API base URL
API_BASE_URL = "https://bible.peplamb.com/api/parse"

# List of Dari book names and their English counterparts
dari_books = [
    ("پیدایش", "Genesis"),
    ("خروج", "Exodus"),
    ("لویان", "Leviticus"),
    ("اعداد", "Numbers"),
    ("تثنیه", "Deuteronomy"),
    ("یوشع", "Joshua"),
    ("داوران", "Judges"),
    ("روت", "Ruth"),
    ("اول سموئیل", "1 Samuel"),
    ("دوم سموئیل", "2 Samuel"),
    ("اول پادشاهان", "1 Kings"),
    ("دوم پادشاهان", "2 Kings"),
    ("اول تواریخ", "1 Chronicles"),
    ("دوم تواریخ", "2 Chronicles"),
    ("عزرا", "Ezra"),
    ("نحمیا", "Nehemiah"),
    ("استر", "Esther"),
    ("ایوب", "Job"),
    ("مزامیر", "Psalms"),
    ("امثال", "Proverbs"),
    ("جامعه", "Ecclesiastes"),
    ("غزل غزل‌ها", "Song of Solomon"),
    ("اشعیا", "Isaiah"),
    ("ارمیا", "Jeremiah"),
    ("سوگنامه", "Lamentations"),
    ("حزقیال", "Ezekiel"),
    ("دانیال", "Daniel"),
    ("هوشع", "Hosea"),
    ("یوئیل", "Joel"),
    ("عاموس", "Amos"),
    ("عوبدیا", "Obadiah"),
    ("یونس", "Jonah"),
    ("میکاه", "Micah"),
    ("ناحوم", "Nahum"),
    ("حبقوق", "Habakkuk"),
    ("صفنیا", "Zephaniah"),
    ("حجی", "Haggai"),
    ("زکریا", "Zechariah"),
    ("ملاکی", "Malachi"),
    ("متی", "Matthew"),
    ("مرقس", "Mark"),
    ("لوقا", "Luke"),
    ("یوحنا", "John"),
    ("اعمال", "Acts"),
    ("رومیان", "Romans"),
    ("اول قرنتیان", "1 Corinthians"),
    ("دوم قرنتیان", "2 Corinthians"),
    ("غلاطیان", "Galatians"),
    ("افسسیان", "Ephesians"),
    ("فیلیپیان", "Philippians"),
    ("کولسیان", "Colossians"),
    ("اول تسالونیکیان", "1 Thessalonians"),
    ("دوم تسالونیکیان", "2 Thessalonians"),
    ("اول تیموتائوس", "1 Timothy"),
    ("دوم تیموتائوس", "2 Timothy"),
    ("تیطوس", "Titus"),
    ("فیلیمون", "Philemon"),
    ("عبرانیان", "Hebrews"),
    ("یعقوب", "James"),
    ("اول پطرس", "1 Peter"),
    ("دوم پطرس", "2 Peter"),
    ("اول یوحنا", "1 John"),
    ("دوم یوحنا", "2 John"),
    ("سوم یوحنا", "3 John"),
    ("یهودا", "Jude"),
    ("مکاشفه", "Revelation"),
]

# Check each book using the API and collect results for books with length 0
books_with_empty_parse = []
books_with_good_parse = []

for dari, english in dari_books:
    params = {
        "references": dari,
        "splitRange": "true",
    }
    try:
        response = requests.get(API_BASE_URL, params=params, timeout=10)
        if response.status_code == 200:
            data = response.json()
            if len(data) == 0:
                print(f"Book with no parsed references: {dari} ({english})")
                books_with_empty_parse.append((dari, english))
            else:
              books_with_good_parse.append((dari, english))
        else:
            print(f"Error {response.status_code} for {dari} ({english}): {response.text}")
    except requests.exceptions.RequestException as e:
        print(f"Request failed for {dari} ({english}): {e}")

# Output results as a table
# print("Books with no parse results:")
df_dari_bad = pd.DataFrame(books_with_empty_parse, columns=["Dari Name", "English Name"])
# print("Books with good parse results:")
df_dari_good = pd.DataFrame(books_with_good_parse, columns=["Dari Name", "English Name"])

Book with no parsed references: غزل غزل‌ها (Song of Solomon)
Book with no parsed references: سوگنامه (Lamentations)
Book with no parsed references: تیطوس (Titus)

In [4]:
df_dari_bad

    Dari Name     English Name
0  غزل غزل‌ها  Song of Solomon
1     سوگنامه     Lamentations
2       تیطوس            Titus